remove 'gas now' API from gas price query
Synthetixio/js-monorepo pull request #118
Opened 2021-11-02 18:28 UTC by kmeraz

2021-11-02 18:40 UTC, fritzschoff commented
ref #117

2021-11-08 07:41 UTC, fritzschoff approved these changes

2021-11-08 11:44 UTC, 0xclem requested changes

2021-11-08 11:44 UTC, 0xclem commented on packages/queries/__tests__/network.test.ts
> +			newCTX.provider!,
@kmeraz can you please fix the linter warnings?

2021-11-08 11:44 UTC, 0xclem commented on packages/queries/src/queries/network/useEthGasPriceQuery.ts
> +import { BigNumber } from 'ethers';
I don't think we should be using this lib since we've got the `Wei` one now

2021-11-08 11:44 UTC, 0xclem commented on packages/queries/src/queries/network/useEthGasPriceQuery.ts
> +						fastest: block.baseFeePerGas
It's great that you added a EIP 1159 support. However what is this formula? You are multiplying `baseFeePerGas` by 2 and then adding some wei on top of that?

2021-11-08 14:00 UTC, fritzschoff commented on packages/queries/src/queries/network/useEthGasPriceQuery.ts
> +						fastest: block.baseFeePerGas
The formula is from a blocknative blog post. 2 times blockBasFee with some premium for the miner. I didn't want to create two return types, that is why I squeezed that into this type structure. But that is highly questionable

2021-11-09 02:08 UTC, bachstatter commented on packages/queries/src/queries/network/useEthGasPriceQuery.ts
> +const MULTIPLIER = new Wei(2, 1).toBN();
I think we usually just do use `wei()` rather than `new Wei()` def no biggie 😅

2021-11-09 02:08 UTC, bachstatter approved these changes

2021-11-09 02:09 UTC, bachstatter commented
Looks like a test is failing too, not sure if it's an actual mistake or assert error

2021-11-09 16:07 UTC, 0xclem requested changes

2021-11-09 16:07 UTC, 0xclem commented on packages/queries/src/queries/network/useEthGasPriceQuery.ts
> +						fastest: block.baseFeePerGas.mul(MULTIPLIER).add(wei(6, 9).toBN()).toNumber(),
Ok so I had a look at the article from Blocknative which explains this method:  https://www.blocknative.com/blog/eip-1559-fees

I'm happy with that, even though the `priority fee` is a bit random (2, 4 or 6). But unfortunately there's no way to really predict it, except using blocknative API maybe?

https://www.blocknative.com/gas-estimator

Another thing. Before merging this PR, we need to change the structure of this object a bit because I believe (correct me if I'm wrong) there is no way for the frontend to now which one to use (EIP1559 or before).

The object always returns the same `{average: value, fast: value, fastest: value}` and this isn't correct.

For EIP1559 it should probably be something like:

`{average: { maxFeePerGas:  block.baseFeePerGas.mul(MULTIPLIER).add(wei(2, 9).toBN()).toNumber()     maxPriorityFeePerGas: wei(2, 9).toBN().toNumber()}, fast: ...etc, fastest: ...etc}`

Because the params for an EIP1559 transaction are different. And the frontend needs to know which ones to pass in a call.

2021-11-09 17:11 UTC, dbeal-eth requested changes
I think there is a math error in the code here with `MULTIPLIER`. Also, I think we should be returning `maxBaseFee` and `maxPriorityFee` separately, since you don't really get 90% of the benefit of 1559 without having them separate. I also think we should do-away with `fast`, `fastest`, and `average` and just have. If the user want's more speed for some reason, almost every wallet supports their own system.

I'm sure you already know, but when having these values separately, during normal operation, the miner gets paid the `maxPriorityFee`, while the transaction sender only pays whatever the `baseFee` was at the block the transaction got included in. Therefore, the user saves `maxBaseFee - baseFee` gas. If you don't keep these values separate, the user ends up paying the full amount of `maxBaseFee` since the miner gets paid the full remainder.

2021-11-09 17:11 UTC, dbeal-eth commented on packages/queries/src/queries/network/useEthGasPriceQuery.ts
> +const MULTIPLIER = wei(2, 1).toBN();
note: this value would be `20`, not 2 as I imagine you would expect. So, if the gas is `150 gwei`, that would be multiplying by 20 to `3000 gwei` right?

2021-11-15 18:51 UTC, closed without merging