removed lerna
Synthetixio/js-monorepo pull request #185
Opened 2022-04-07 10:43 UTC by fritzschoff

2022-04-16 09:11 UTC, bachstatter commented on .github/workflows/main.yml
> +          node-version: '16.x'
I think we should use `ghcr.io/synthetixio/docker-node/alpine:16.14`,
Staking uses that container (although still on 14)
https://github.com/Synthetixio/staking/blob/dev/.github/workflows/audit_build_verify.yml#L37

You can see available versions here:
https://github.com/orgs/Synthetixio/packages/container/package/docker-node%2Falpine

This docker container comes with `yarn` installed so we can skip `npm i -g yarn` below.

2022-04-16 09:12 UTC, bachstatter commented on .github/workflows/main.yml
> +      - run: yarn run lint:fix
Probably dont want to fix in CI. We like the code we commit to be the same in the package. Should be up to the dev to fix before hand

2022-04-16 09:13 UTC, bachstatter commented on .github/workflows/main.yml
> +      - run: yarn run test
Will this run the test for all components? I think it should be `yarn workspaces run test`
(https://classic.yarnpkg.com/en/docs/cli/workspaces#toc-yarn-workspaces-run)

2022-04-16 09:15 UTC, bachstatter commented on .github/workflows/main.yml
> +          npm -w contracts-interface version 0.0.0-$(git rev-parse --short origin/${{ github.head_ref }})
Should we be using yarn here? `yarn workspace version 0.0.0-$(git rev-parse --short origin/${{ github.head_ref }})`

2022-04-16 09:16 UTC, bachstatter commented on .github/workflows/updateDependency.yml
> +      - run: pm -w contracts-interface publish --tag latest
typo here `pm` -> `npm`. But as said above I think we should be using yarn

2022-04-16 09:18 UTC, bachstatter commented on package.json
> +	],
This is a slightly annoying comment. But to me it make sense to keep the `packages` folder. 
and have the workspace be `"workspaces": [ "packages/*]`.
Two reasons: 
1. That's usually what I see in other monorepos.
2. If we add a new package it will be picked up automatically

2022-04-16 09:20 UTC, bachstatter commented on package.json
> +		"webpack-cli": "^4.9.2"
Do we need the dependencies here? I thought yarn workspaces would take care of that? 
Or does running `yarn install` produce these dependencies automatically?

2022-04-16 09:22 UTC, bachstatter requested changes
Left some comments. Can have a chat next week

2022-04-18 10:31 UTC, fritzschoff commented on .github/workflows/main.yml
> +      - run: yarn run test
yes it runs for all the workspaces

2022-05-27 15:42 UTC, fritzschoff commented on package.json
> +	],
doesn't that include node_modules and .github dirs?

2022-05-30 08:32 UTC, closed without merging