replace bytes32 with ethers equivalent
Synthetixio/js-monorepo pull request #257
Opened 2022-08-18 01:19 UTC by jmzwar

2022-08-18 06:02 UTC, bachstatter approved these changes

2022-08-18 06:17 UTC, bachstatter requested changes
Looks like `useFeeReclaimPeriodsQuery` still relies on synths.

2022-08-19 04:13 UTC, bachstatter commented on packages/queries/src/queries/shorts/useShortsQuery.ts
> +      const synth = SynthsByName[currencyKey];
hmm yea I guess `generateSynths` in `contracts` could just as well generate a function instead of a lookup object

2022-08-19 04:15 UTC, jmzwar commented on packages/queries/src/utils.ts
> +    case NetworkIdByName['goerli']:
nice

2022-08-19 04:17 UTC, bachstatter commented on packages/queries/src/utils.ts
> +export const loadSynthsByNameFromNetwork = (networkId: NetworkId) => {
hmm yea maybe. Although since since is consumed by react-query hooks I sorta find it easier to have it as a function.
But it's probably a good hook to have too

2022-08-19 05:02 UTC, bachstatter approved these changes

2022-08-19 05:03 UTC, jmzwar commented on packages/queries/src/utils.ts
> +export const loadSynthsByNameFromNetwork = (networkId: NetworkId) => {
I reckon that is a good idea for some of the bigger contracts (or even bundles of them) that are getting 200k +, but here I think these are basically synchronous speed.

2022-08-19 05:33 UTC, bachstatter commented on packages/queries/src/utils.ts
> +export const loadSynthsByNameFromNetwork = (networkId: NetworkId) => {
yea I know that.  But say I wanted to use it here instead of `loadSynthsByNameFromNetwork`:
```
const useFeeReclaimPeriodsQuery = (
  ctx: QueryContext,
  walletAddress: string,
  options?: UseQueryOptions<SynthFeeAndWaitingPeriod[]>
) => {
  return useQuery<SynthFeeAndWaitingPeriod[]>(
    ['synths', 'feeReclaimPeriods', ctx.networkId],
    async () => {
      if (!ctx.snxjs || !ctx.networkId) return [];
      const { SynthsByName } = await loadSynthsByNameFromNetwork(ctx.networkId);
      ...<more logic>...
```
I would then call then have to use `synthsQuery.data` in  `enabled`:
```
const synthsQuery = useSynths(networkId)
return useQuery(    ['synths', 'feeReclaimPeriods', ctx.networkId], () => {
      if(!synthsQuery.data) throw Error('Expected data')
      const { SynthsByName } =  synthsQuery.data
       ...<more logic>...
  }, 
  { enabled: synthsQuery.data }
}
```
And since react query/ ts isn't smart enough to  know that it's always will be defined I have to add that ugly `throw`

Also while `synthsQuery` is fetching consumers of this hook will still see the query as `idle` rather than `loading` since the query we return hasn't been enabled yet. 

I do feel like I'm missing something regarding dependent queries like, maybe you can enlighten me  hehe?

2022-08-19 05:34 UTC, bachstatter commented on packages/queries/src/queries/shorts/useShortsQuery.ts
> +      const synth = SynthsByName[currencyKey];
I guess in a few places we want to get an array with all synths and do ` Object.values(SynthsByName)`.
But we could have `generateSynths` in `contracts` generate both a function and a lookup object?

2022-08-21 23:29 UTC, bachstatter commented on packages/queries/src/utils.ts
> +export const loadSynthsByNameFromNetwork = (networkId: NetworkId) => {
yea that works. But the hook will report the status as `idle` while `useSynths(networkId)` is fetching. Only when `useSynths` is done will the query accurately report `isFetching`

Also, probably more important, the error handling gets a little tricker. If `useSynths(networkId)` has an error the query we return will never be enabled. So the error will be swallowed and the query will be in an `idle` state.

Both of this problem works automatically when using a function, and we can also remove the`if(!synthsQuery.data) throw Error('Expected data')` check.

2022-08-21 23:56 UTC, jmzwar commented on packages/queries/src/utils.ts
> +export const loadSynthsByNameFromNetwork = (networkId: NetworkId) => {
Yep - agree with Joey in this particular case. Really a hook is just an abstraction to allow async functionality to be rendered nicely in a UI (loading, data, error etc). That async functionality within the hook can be handled by a single function (including say with a Promise.all() if it has different dependencies). Hooks within hooks can get messy.

That said it would be nice to have a useSynths query - say if we were rendering a list of supported synths on a particular page.

2022-08-21 23:59 UTC, bachstatter commented on packages/queries/src/utils.ts
> +export const loadSynthsByNameFromNetwork = (networkId: NetworkId) => {
Yep I did add that hook and will be using it in staking:
Commit adding the hook https://github.com/Synthetixio/js-monorepo/pull/257/commits/47582ba90794f927e3cb6674d93ce6b841b43784

And using it here: 
https://github.com/Synthetixio/staking/pull/1230/commits/d80822781316b09a79a18e6813d7bc8761738270

(well almost that hook returning a "lookup" object instead of a array)

2022-08-22 00:06 UTC, jmzwar commented on packages/queries/src/utils.ts
> +export const loadSynthsByNameFromNetwork = (networkId: NetworkId) => {
Yeah nice. I really like this pattern. We do get the nice async import in a hook, and then if the synths change on another deployment there is minimal changes we need to make other than running codegen and upgrading.

2022-08-22 03:06 UTC, merged