fix: add missing negative entries in debt pool share compute
Synthetixio/js-monorepo pull request #28
Opened 2021-06-18 12:06 UTC by vbstreetz

2021-07-02 16:33 UTC, KillerByte requested changes
we talked in private conversation and agreed since rest of queries uses `wei` library, numbers exported by this function should also use `wei`.

2021-07-02 17:01 UTC, vbstreetz commented
> we talked in private conversation and agreed since rest of queries uses `wei` library, numbers exported by this function should also use `wei`.

awesome. on it..

2021-07-28 15:41 UTC, vbstreetz commented
> > we talked in private conversation and agreed since rest of queries uses `wei` library, numbers exported by this function should also use `wei`.
> 
> awesome. on it..

hey! i just pushed an update to fix this.

2021-07-30 15:48 UTC, vbstreetz commented
This has been successfully integrated in stats https://stats-git-use-synthetix-queries-pkg-synthetixio.vercel.app

<img width="606" alt="Screenshot 2021-07-30 at 18 24 42" src="https://user-images.githubusercontent.com/60554509/127678600-9e5a27bd-d3b6-48a0-a8e2-b17919ace049.png">

2021-08-05 16:31 UTC, JChiaramonte7 approved these changes
lgtm

2021-08-05 16:35 UTC, KillerByte approved these changes
please fix a couple things but overall really appreciate :+1:

2021-08-05 16:35 UTC, KillerByte commented on packages/queries/__tests__/synths.test.ts
> +		const [sETHKey, sBTCKey, sUSDKey] = [Synths.sETH, Synths.sBTC, Synths.sUSD].map(
this constant isnt great, but its probably fine for now.

2021-08-05 16:35 UTC, KillerByte commented on packages/queries/__tests__/synths.test.ts
> +		const [sETHKey, sBTCKey, sUSDKey] = [Synths.sETH, Synths.sBTC, Synths.sUSD].map(
instead it should let the end user application send in the list of keys they want, not hardcoded here.

2021-08-05 16:35 UTC, KillerByte commented on packages/queries/package.json
> +		"@synthetixio/data": "0.0.0-3bc863c",
make sure this doesn't  get pushed

2021-08-05 16:44 UTC, vbstreetz commented on packages/queries/package.json
> +		"@synthetixio/data": "0.0.0-3bc863c",
plan is to resolve this in a follow-up PR..

2021-08-05 17:21 UTC, merged