Real data v2 home
Synthetixio/js-monorepo pull request #332
Opened 2022-09-14 05:25 UTC by bachstatter

- Fixes up some inconsistencies with network id. 
- Use container pattern for v2-components
- Rename Banner to CRatioBanner and make the text dynamic
- Include `liquidationDeadlineForAccount` in debt data (this is how we know if someone is flagged)

There still some todo's in here, but might be worth getting some feedback on the architecture. Happy to continue working on this branch or create a new PR resolving the todos.

Also build is failing due to some problems with types. When it's fixed and #331  is merged I'll rebase

2022-09-14 06:56 UTC, jmzwar reviewed
Looks good. Just the two questions.

2022-09-14 06:56 UTC, jmzwar commented on v2/components/BalanceBox/BalanceBox.tsx
> +export const BalanceBox: React.FC<Props> = ({ networkId, provider, walletAddress }) => {
Is the intention to keep the wrapper component in the same file as the UI component?

2022-09-14 06:56 UTC, jmzwar commented on v2/components/CRatioBanner/CRatioBanner.tsx
> +  }
Would it be possible to just return the bgGradient or bgColor here rather than the wrapper component? And then call the function in the props of the actual wrapper?

2022-09-14 07:29 UTC, noisekit approved these changes
I really like how the ui/container component separation works out 💪

2022-09-14 07:35 UTC, bachstatter commented on v2/components/BalanceBox/BalanceBox.tsx
> +export const BalanceBox: React.FC<Props> = ({ networkId, provider, walletAddress }) => {
yep

2022-09-14 07:36 UTC, bachstatter commented on v2/components/BalanceBox/BalanceBox.tsx
> +}: PropsWithChildren<UiProps>) => {
Yea I'm not fussed about this.. I think I would do inline unless there's quite a few props normally. Can change to inline

2022-09-14 07:38 UTC, bachstatter commented on v2/components/CRatioHealthCard/CRatioHealthCard.tsx
> +            {Math.round(currentCRatioPercentage)}%
hmm yea maybe.. did consider this. I think the contracts have a little bit on a buffer for ratio's so probably doesn't matter too much

2022-09-14 07:41 UTC, bachstatter commented on v2/lib/useSynthetixContracts/useSynthetixContracts.ts
> +    [contractNames, networkId],
hmm yea. I did consider it, but thought it would be quite common to grab a few contracts in the hooks. `useDebtData` uses 3. And it gets a little uglier to have three react-queries added to enabled.. But if types just works its probably worth it

2022-09-14 07:42 UTC, bachstatter commented on v2/components/CRatioBanner/CRatioBanner.tsx
> +  }
yea sure

2022-09-14 11:51 UTC, bachstatter commented on v2/lib/useSynthetixContracts/useSystemSettings.ts
> +  const { address, abi } = await contracts['SystemSettings'][networkName]();
yep def, fixed

2022-09-14 11:52 UTC, bachstatter commented on v2/lib/useSynthetixContracts/useSynthetixContracts.ts
> +    [contractNames, networkId],
types is working out so moving to this structure

2022-09-15 01:19 UTC, bachstatter commented on v2/ui/content/V2Home.tsx
> +          <MainActionCards {...propsFromConnector} />
We still dont have a context to get network id and the provider from the Connector container. So for now I use props for that

2022-09-15 01:23 UTC, bachstatter commented on v2/ui/content/V2Home.tsx
> +        <CRatioBanner {...propsFromConnector} />
It's quite an effort to move the connector to a separate package

2022-09-15 05:14 UTC, bachstatter commented on v2/ui/content/V2Home.tsx
> +        <CRatioBanner {...propsFromConnector} />
Using a context for this now

2022-09-15 05:15 UTC, bachstatter commented on v2/ui/content/V2Home.tsx
> +          <MainActionCards {...propsFromConnector} />
Using context for this now

2022-09-15 05:36 UTC, noisekit requested changes

2022-09-15 05:39 UTC, bachstatter commented on v2/ui/App.tsx
> +            walletAddress,
Lets have a chat about this. The idea to have a default provider and a default network is that we can fetch data before the user is connected.  But yea we could just instantiate a default provider/network in each contract hook if we want to keep the context small

2022-09-15 05:39 UTC, jmzwar approved these changes

2022-09-16 00:46 UTC, noisekit approved these changes
Love this very much

2022-09-16 00:48 UTC, bachstatter commented on v2/ui/content/V2Home.tsx
> +          <MainActionCards />
😌

2022-09-16 00:48 UTC, merged