Subgraphs v3
Synthetixio/js-monorepo pull request #475
Opened 2022-11-07 12:19 UTC by fritzschoff

2022-11-07 12:52 UTC, noahlitvin requested changes

2022-11-07 12:52 UTC, noahlitvin commented on v3/subgraphs/schema.graphql
> +type PoolCreated @entity {
rename to `Pool`

2022-11-07 12:52 UTC, noahlitvin commented on v3/subgraphs/schema.graphql
> +  timestamp: BigInt!
rename to `created_at`

2022-11-07 12:52 UTC, noahlitvin commented on v3/subgraphs/schema.graphql
> +  owner: Bytes!
Is there an Address type or is this supposed to be Bytes? I forget...

2022-11-07 13:35 UTC, fritzschoff commented on v3/subgraphs/schema.graphql
> +  owner: Bytes!
![Bildschirmfoto 2022-11-07 um 14 34 59](https://user-images.githubusercontent.com/39312833/200323588-f777dc57-d024-4537-9a90-2d92f32430d4.png)
dont't think so. Maybe String?

2022-11-07 13:39 UTC, fritzschoff commented on v3/subgraphs/schema.graphql
> +  owner: Bytes!
![Bildschirmfoto 2022-11-07 um 14 38 53](https://user-images.githubusercontent.com/39312833/200324373-1c26eeb8-c956-4c35-bfc9-30456b4a9d35.png)
Bytes is suggested by the CLI

2022-11-07 13:45 UTC, fritzschoff commented on v3/subgraphs/schema.graphql
> +  owner: Bytes!
Will go with Bytes

2022-11-08 13:11 UTC, fritzschoff commented on .eslintignore
> +**/generated
and how do you handle the complaints from es lint when it doesn't fit into the rules?

2022-11-08 13:11 UTC, fritzschoff commented on v3/subgraphs/package.json
> +    "@graphprotocol/graph-ts": "0.28.1"
will do

2022-11-24 00:35 UTC, bachstatter commented on v3/subgraphs/src/core.ts
> +    if (position.total_burned && position.total_burned) {
This should be `position.total_burned && position.total_minted`

2022-11-24 07:40 UTC, fritzschoff commented on v3/subgraphs/src/core.ts
> +    if (position.total_burned && position.total_burned) {
Thanks but already fixed locally. It also changed a bit

2022-11-25 10:11 UTC, fritzschoff commented on .circleci/config.yml
> +      - run: yarn workspace @snx-v3/subgraphs test
seems pretty buggy. all the pool handlers are tested.

2022-11-25 10:13 UTC, fritzschoff commented on .circleci/config.yml
> +      - run: yarn workspace @snx-v3/subgraphs test
![Bildschirmfoto 2022-11-25 um 10 12 17](https://user-images.githubusercontent.com/39312833/203958803-1c34c556-60d0-49df-8eeb-bd9e895fa503.png)
![Bildschirmfoto 2022-11-25 um 10 12 28](https://user-images.githubusercontent.com/39312833/203958812-c36c7232-c9cd-4b68-bf0c-50245260bba9.png)
![Bildschirmfoto 2022-11-25 um 10 12 42](https://user-images.githubusercontent.com/39312833/203958817-ccf4107a-24bb-4099-b249-6c8f5642e19f.png)
![Bildschirmfoto 2022-11-25 um 10 12 52](https://user-images.githubusercontent.com/39312833/203958821-73d56cdb-d3f4-451e-ba90-add6aea790a5.png)

2022-11-25 10:17 UTC, fritzschoff commented on .circleci/config.yml
> +      - run: yarn workspace @snx-v3/subgraphs test
![Bildschirmfoto 2022-11-25 um 10 17 07](https://user-images.githubusercontent.com/39312833/203960364-6424fddc-bf65-4ad2-a332-e15904339bd9.png)
you have to reexport the handlefunctions in the test file in order to make them visible for the coverage tool...

2022-11-25 10:23 UTC, fritzschoff commented on .eslintrc.js
> +    },
thank you!

2022-11-25 11:19 UTC, fritzschoff commented
All the entities that are present are important according to @noahlitvin but I let him decide if we want to shrink the subgraph.
@noahlitvin please make the call

2022-11-25 11:23 UTC, fritzschoff commented on v3/subgraphs/tests/.latest.json
> +{
will remove it all good

2022-11-25 14:16 UTC, noahlitvin approved these changes

2022-11-25 14:17 UTC, merged