Subgraph market snapshot
Synthetixio/js-monorepo pull request #562
Opened 2022-12-11 23:03 UTC by bachstatter

This PR:
- Extract out market event handlers to a seperate file, and separately tested 
- Add a new MarketSnapshot Entity
- Make sure that a MarketSnapshot entity is created everytime someone deposit/withdraws from a market

2022-12-11 23:27 UTC, bachstatter commented on v3/subgraphs/goerli/src/market.ts
> +  const newMarketSnapshot = new MarketSnapshot(marketId.concat('-').concat(timestamp.toString()));
This would happen everytime someone withdrawals or deposit for a market. The marketID + Timestamp is a true identifier for this entity in my mind. We could add a block number too but not sure it adds any value.
Or did you have anything else in mind

2022-12-11 23:28 UTC, bachstatter commented on v3/subgraphs/goerli/tests/market.test.ts
> +    const now = new Date(1668448739566).getTime();
Yea agree I changed the other market test to have simpler timestamps. Will change this too

2022-12-12 11:23 UTC, bachstatter commented
We know have a few more entities:
`Market`: Stay the same, will contain the most recent values
`MarketSnapshotByBlock`: Stores every market update for each block, if there's two market events in the same block they would be aggregate
`MarketSnapshotByDay`: Stores every market update for each day, all updates during the same UTC day will be aggregated
`MarketSnapshotByWeek`: Same thing but for week.

We talked about doing it more event source:y and have the handlers totally isolated.
But since we all depend on the most recent Market values in some cases I opted to just pass the updated Market.

2022-12-12 11:37 UTC, fritzschoff requested changes

2022-12-12 11:37 UTC, fritzschoff commented on v3/subgraphs/goerli/schema.graphql
> +  block_number: BigInt!
out of consistency I would add created_at and created_at_block.
Same with udpated_at + block
I guess you did that with timestamp and block_number, so maybe just rename it!

2022-12-12 11:37 UTC, fritzschoff commented on v3/subgraphs/goerli/tests/marketSnapshotByBlock.test.ts
> +    const newMarketRegisteredEvent = createMarketCreatedEvent(1, address, now, now - 1000);
so you creating a market with a block number -999 ? I mean technically not wrong but weird test fixture.
Would argue to do it the way we had it.

2022-12-12 11:37 UTC, fritzschoff commented on v3/subgraphs/goerli/tests/marketSnapshotByBlock.test.ts
> +      now + 2000,
same time as event above. Maybe you want to change that

2022-12-12 11:41 UTC, bachstatter commented on v3/subgraphs/goerli/schema.graphql
> +  block_number: BigInt!
Hmm yea, I added these before when I was doing when unique marketsnapshot for every update. But now when there's aggregation I guess it does make sense to follow the same structure 👍

2022-12-12 11:45 UTC, bachstatter commented on v3/subgraphs/goerli/tests/marketSnapshotByBlock.test.ts
> +      now + 2000,
I do want that. The timestamp will be the same if two events happen in the same block. And when that's the case we should be updating the existing one rather than creating a new

2022-12-13 01:04 UTC, bachstatter commented on v3/subgraphs/goerli/schema.graphql
> +  block_number: BigInt!
Fixed

2022-12-13 01:04 UTC, bachstatter commented on v3/subgraphs/goerli/tests/marketSnapshotByBlock.test.ts
> +    const newMarketRegisteredEvent = createMarketCreatedEvent(1, address, now, now - 1000);
No minus blocks now

2022-12-13 07:43 UTC, fritzschoff requested changes

2022-12-13 07:43 UTC, fritzschoff commented on v3/subgraphs/goerli/schema.graphql
> +  created_at_block: BigInt!
thanks!

2022-12-13 07:43 UTC, fritzschoff commented on v3/subgraphs/goerli/src/market.ts
> +    return;
weird that you don't get a build error since the function is `void`. Maybe wrap the reset into an else? But up to your gusto

2022-12-13 07:43 UTC, fritzschoff commented on v3/subgraphs/goerli/src/market.ts
> +  createMarketSnapshotByBlock(market);
So this came to my mind, quote from the subgraph docs:
`This more elaborate way of storing many-to-many relationships will result in less data stored for the subgraph, and therefore to a subgraph that is often dramatically faster to index and to query.`
What I mean is that, if we have a lot of entities in the store, this will actually slow down the subgraph.

2022-12-13 07:44 UTC, fritzschoff commented on v3/subgraphs/goerli/src/market.ts
> +  createMarketSnapshotByBlock(market);
https://thegraph.com/docs/en/developing/creating-a-subgraph/#example-2
This is about many to many relations but the idea is the same with the entities

2022-12-13 07:48 UTC, bachstatter commented on v3/subgraphs/goerli/src/market.ts
> +    return;
`return` nothing is `void`

2022-12-13 07:59 UTC, bachstatter commented on v3/subgraphs/goerli/src/market.ts
> +  createMarketSnapshotByBlock(market);
Hmm yea I think having an entity like that does make sense when there's a many to many relationship. It's like a classic many-to-many table. But in our case each marketSnapshot only belong to one market so not sure it will help in this case.

And yea with these entities indexing will be slower, but there's no extra contract calls which perviously has been what really slows down indexing . And fetching of data will be faster,  say we want history over a month or even a week, if we only had data for every block it could get quite big and require pagination + plus frontend aggregation.  With the  aggregation in the subgraph we can calculate the APR based on a markets yearly performance without any problems.  Or show yearly charts etc.

2022-12-13 08:00 UTC, bachstatter commented on v3/subgraphs/goerli/src/market.ts
> +    return;
I prefer an early return for this edge case, we could even throw since this would be an unexpected error. But an error log is quite visible in the subgraphs ui

2022-12-13 08:01 UTC, bachstatter commented
@fritzschoff  I requested review, hoping to get this merged tomorrow

2022-12-13 08:02 UTC, fritzschoff commented on v3/subgraphs/goerli/src/market.ts
> +  createMarketSnapshotByBlock(market);
I see the need, I get that. But the example just points out that if you have many entities indexing will be slower or as the docs say `dramatically`. It is not about many to many relationships, this is there just because this statement was written in relationships section of the docs.

2022-12-13 08:03 UTC, fritzschoff commented on v3/subgraphs/goerli/src/market.ts
> +    return;
ah okay cool, nvm then

2022-12-13 08:12 UTC, bachstatter commented on v3/subgraphs/goerli/src/market.ts
> +  createMarketSnapshotByBlock(market);
Yea of coruse it gets slower, it requires a save in a db for each one. 
But we are following their recommendation for one to many relationship:
> For one-to-many relationships, the relationship should always be stored on the 'one' side, and the 'many' side should always be derived. Storing the relationship this way, rather than storing an array of entities on the 'many' side, will result in dramatically better performance for both indexing and querying the subgraph. In general, storing arrays of entities should be avoided as much as is practical.

2022-12-13 08:30 UTC, fritzschoff approved these changes

2022-12-13 08:41 UTC, fritzschoff commented on v3/subgraphs/goerli/src/market.ts
> +  createMarketSnapshotByBlock(market);
We had a chat and decided that we keep the createMarketByBlock function for now but with a comment that if the subgraph is slowing down, we gonna remove that func.

2022-12-13 23:06 UTC, bachstatter commented
After a call with max yesterday I decided to remove MarketSnapshotByBlock. Two reasons:
-  He had been working with some subgraphs being slow and flakey due to entities with lots of item.
-  At the moment we dont have any requirement to show block granularity, and even in the future when we build charts daily might be fine

2022-12-14 00:54 UTC, bachstatter commented on v3/subgraphs/goerli/tests/marketSnapshotByWeek.test.ts
> +    // @ts-ignore
hmm yea this is for vscode.. Is webstorm smart enough to figure out that this is assembly script?

2022-12-14 00:58 UTC, bachstatter commented on v3/subgraphs/goerli/schema.graphql
> +type MarketSnapshotByDay @entity {
I guess we could if we add a `aggregation_period` field. The id structure would be different depending on that field too then.  Do you think that's better?

2022-12-14 01:01 UTC, bachstatter commented on v3/subgraphs/goerli/tests/marketSnapshotByWeek.test.ts
> +    // @ts-ignore
Most of the types are correct, there are just in some cases where we use global stuff that exists in assembly script it gets confused

2022-12-14 02:25 UTC, bachstatter commented on v3/subgraphs/goerli/schema.graphql
> +type MarketSnapshotByDay @entity {
hmm say I only want weekly snapshots for the last 6months. I cant query that without getting all the daily snapshots too if they dont have a field that differentiate them. 

It would also obv work fine to have it like we have it now

2022-12-14 03:54 UTC, merged