fix(queries): added decimal argument to wei conversion in token balance query
Synthetixio/js-monorepo pull request #59
Opened 2021-08-16 22:30 UTC by JChiaramonte7

We were converting all currency balances to wei with the default 18 decimal standard. This fixes the conversation for tokens that don't use 18 decimals (ie. USDC, USDT)

2021-08-16 22:44 UTC, kmeraz approved these changes

2021-08-17 09:22 UTC, KillerByte requested changes

2021-08-17 09:22 UTC, KillerByte commented on packages/queries/src/queries/walletBalances/useTokensBalancesQuery.ts
> +					balance: wei(balance, token.decimals, true),
is `token.decimals` nullable? if so, should add default to 18. in fact, might want to declare the input type here at this point rather than just leaving it as `any`.

also, `wei` automatically interprets `BigNumber` types to be `asWei = true` already, so specifying the last argument is not necessary. typically I only provide the argument as an override

2021-08-17 20:03 UTC, JChiaramonte7 commented on packages/queries/src/queries/walletBalances/useTokensBalancesQuery.ts
> +					balance: wei(balance, token.decimals, true),
fixed and going to merge so i can fix kwenta, but if fixes weren't sufficient let me know

2021-08-17 20:04 UTC, merged