Feature/filtering
Synthetixio/js-monorepo pull request #878
Opened 2023-05-21 23:20 UTC by jmzwar

Markets working - size slightly changed (removed $) to filter size just on asset size.

2023-05-22 00:26 UTC, bachstatter commented on v2/perps-v2/ui/src/hooks/useActions.ts
> +        size_lte: max ? wei(max).toBN().toString() : undefined, // Should be divided by current price
What does should be divided by current mean?

2023-05-22 00:30 UTC, bachstatter commented
Size is in native units? Would be nice to mention that.. Or maybe update the graph so we can use dollar size filter.. As of now you cant really use the size filter for all markets
![Screenshot 2023-05-22 at 10 28 23 am](https://github.com/Synthetixio/js-monorepo/assets/5688912/f3c30c96-d629-464f-b00c-1ca8aea75510)

2023-05-22 00:31 UTC, bachstatter commented
Selected markets not showing up and the popup is closed, is that expected?
![Screenshot 2023-05-22 at 10 28 16 am](https://github.com/Synthetixio/js-monorepo/assets/5688912/815e3c08-6dc6-48ee-b47a-3725e1cf5217)
![Screenshot 2023-05-22 at 10 30 48 am](https://github.com/Synthetixio/js-monorepo/assets/5688912/23bbb5c8-9fad-4fcb-bfce-c09ee332c230)

2023-05-22 00:50 UTC, jaderns commented
Supporting Joey's feedback. 
Can we make both filters apply when click? As in results reload as you select a market and as you type in the value for size? 
Size filter should ideally be in dollar unit
When popup closed, selected markets should be displayed (see ss)
<img width="311" alt="Screenshot 2023-05-22 at 10 48 42" src="https://github.com/Synthetixio/js-monorepo/assets/57506148/f1b94d3a-c8df-4a3c-892d-2879d78de95d">

2023-05-22 01:30 UTC, jmzwar commented on v2/perps-v2/ui/src/hooks/useActions.ts
> +        size_lte: max ? wei(max).toBN().toString() : undefined, // Should be divided by current price
This means the current price - but yeah I went with native assets to make it easier.

2023-05-22 07:06 UTC, jmzwar commented on v2/perps-v2/ui/src/components/Shared/MarketSelect/MarketSelect.tsx
> +                  setActiveAssets([...activeAssets, market]);
Hmm I'm not too worried about the query string. Results are sorted ofc by timestamp

2023-05-22 07:06 UTC, jmzwar commented on v2/perps-v2/ui/src/utils/constants.ts
> +    id: '0x2b3bb4c683bfc5239b029131eef3b1d214478d93',
Yeah true but too lazy now

2023-05-25 00:51 UTC, bachstatter commented
<img width="1019" alt="Screenshot 2023-05-25 at 10 49 37 am" src="https://github.com/Synthetixio/js-monorepo/assets/5688912/c5250e26-c31a-4b4c-ab04-df3d5c6c7bed">
<img width="1004" alt="Screenshot 2023-05-25 at 10 49 30 am" src="https://github.com/Synthetixio/js-monorepo/assets/5688912/88f66323-10d7-4380-a2ae-a335e55e7b37">
Filter doesn't seem to work for me?

2023-05-25 00:51 UTC, bachstatter commented
<img width="536" alt="Screenshot 2023-05-25 at 10 50 00 am" src="https://github.com/Synthetixio/js-monorepo/assets/5688912/cb1aae5c-d597-4876-b81a-bdf70a240dc5">
Size not showing up in input field

2023-05-25 06:15 UTC, bachstatter requested changes
See comments

2023-05-29 03:20 UTC, bachstatter approved these changes
I pushed up one commit to ensure min/max gets set from query params. Nikita's comments makes sense too..

2023-05-29 03:57 UTC, merged