Watcher auto updates
Synthetixio/js-monorepo pull request #955
Opened 2023-09-08 01:28 UTC by bachstatter

This PR fetches pyth ids from `offchain-feeds.json` instead of hardcoding them
Also needed a marketSummaries hook.

With all the new markets I was also running into 413 from the subgraph. This means our reqeuest payload was too large, so I removed fields we we were not using

2023-09-08 06:26 UTC, bachstatter commented
> How about limiting graph response to like 100 rows or smth?

It was actually not the response that was the problem, they do add pagination and have a max page size.. 
This error we ran into was the *request* query being too big, eg not the response.

2023-09-08 12:12 UTC, jmzwar requested changes
This is good @bachstatter however we also need the contract addresses for each market to be able to fetch them for the market page.

2023-09-09 07:36 UTC, bachstatter commented on v2/perps-v2/ui/src/hooks/useMarketSummaries.ts
> +          res.map((x) => ({ asset: parseBytes32String(x.asset), address: x.market.toLowerCase() }))
@jmzwar  That's why I added this hook

2023-09-09 15:24 UTC, jmzwar commented on v2/perps-v2/ui/src/hooks/useMarketSummaries.ts
> +          res.map((x) => ({ asset: parseBytes32String(x.asset), address: x.market.toLowerCase() }))
Hmm ok - I didn't see the new markets on the markets page. Checking now

2023-09-09 17:15 UTC, jmzwar commented on v2/perps-v2/ui/src/hooks/useMarketSummaries.ts
> +          res.map((x) => ({ asset: parseBytes32String(x.asset), address: x.market.toLowerCase() }))
Ok I think we just don't have enough historical data yet. Gtm

2023-09-09 17:15 UTC, jmzwar approved these changes

2023-09-09 17:41 UTC, merged